name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

defaults:
  run:
    working-directory: website

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: Cache code outputs
        id: cache-code-outputs
        uses: actions/cache@v3
        env:
          cache-name: cache-code-outputs
        with:
          path: website/build/solutions
          key: cache-z3-outputs # currently using a string as a key

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build